# Generated by Django 4.0 on 2021-12-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_user',
            new_name='user',
        ),
    ]
