# Generated by Django 4.0 on 2021-12-29 22:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpeg', force_format='JPEG', keep_meta=True, quality=75, size=[200, 200], upload_to='profile_pics'),
        ),
    ]
