# Generated by Django 4.0 on 2021-12-31 23:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format='JPEG', keep_meta=True, quality=75, size=[100, 100], upload_to='profile_pics'),
        ),
    ]
