# Generated by Django 4.0 on 2021-12-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_author_post_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
