# Generated by Django 4.0 on 2021-12-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20211231_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(choices=[('review', 'review'), ('publised', 'published')], to='posts.Tag'),
        ),
    ]
