# Generated by Django 4.0 on 2022-01-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_category_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('public', 'public'), ('personal', 'personal')], max_length=100, null=True),
        ),
    ]
