# Generated by Django 4.0 on 2022-01-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(choices=[('celebrate', 'celebrate'), ('planning', 'planning'), ('outdoor', 'outdoor'), ('holidays', 'holidays'), ('festivals', 'festivals'), ('movies', 'movies'), ('shopping', 'shopping'), ('laptop', 'laptop')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.category'),
        ),
    ]
