# Generated by Django 4.0 on 2022-01-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_category_name_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('celebrate', 'celebrate'), ('planning', 'planning'), ('outdoor', 'outdoor'), ('holidays', 'holidays'), ('festivals', 'festivals'), ('movies', 'movies'), ('shopping', 'shopping'), ('laptop', 'laptop')], max_length=100, null=True),
        ),
    ]
