# Generated by Django 4.0 on 2022-01-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('celebrate', 'celebrate'), ('planning', 'planning'), ('outdoor', 'outdoor'), ('holidays', 'holidays'), ('festivals', 'festivals'), ('movies', 'movies'), ('shopping', 'shopping'), ('laptop', 'laptop'), ('data', 'data'), ('sciance', 'science'), ('summers', 'summers'), ('medical', 'medical'), ('art', 'art')], max_length=100, null=True),
        ),
    ]
