# Generated by Django 4.0 on 2022-01-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_comment_comment_text_comment_date_posted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment_post',
        ),
    ]
