# Generated by Django 4.0 on 2022-01-02 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_rename_post_comment_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.post'),
        ),
    ]
