# Generated by Django 4.0 on 2022-01-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_remove_comment_comment_post_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment_post',
        ),
    ]
