# Generated by Django 4.0 on 2022-01-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_comment_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('celebrate', 'celebrate'), ('planning', 'planning'), ('outdoor', 'outdoor'), ('holidays', 'holidays'), ('festivals', 'festivals'), ('movies', 'movies'), ('shopping', 'shopping'), ('laptop', 'laptop'), ('data', 'data'), ('science', 'science'), ('summers', 'summers'), ('medical', 'medical'), ('art', 'art')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('reply_comment', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
            ],
        ),
    ]
