name: Django_app_two

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.1]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: create python environment 
      run: python3 -m venv .venv
    - name: Install Dependencies
      run: |
        source .venv/bin/activate
        python3 -m pip install --upgrade pip
    - name: install requirtements    
      run: |
        pip install Django_app_two/wagwan/requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

        
